modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Mechanical-Skies/vs-shields/issues"

[[mods]]
modId="vs_shields"
version="${version}"
displayName="VS Shields"
displayURL="https://www.curseforge.com/minecraft/mc-mods/vs-shields"
logoFile="icon.png"
authors="LennyPane"
description='''
Adds energy shields to Valkyrien Skies 2 ships.
'''

[[dependencies.vs_shields]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.vs_shields]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.vs_shields]]
modId="valkyrienskies"
mandatory=true
versionRange="[2.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.vs_shields]]
modId="architectury"
mandatory=true
versionRange="[9.0.0,)"
ordering="NONE"
side="BOTH"